# Generated by Django 4.2.7 on 2025-07-20 17:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VoiceTranscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("audio_filename", models.CharField(max_length=255)),
                ("transcription_text", models.TextField()),
                ("confidence_score", models.FloatField(blank=True, null=True)),
                (
                    "model_used",
                    models.CharField(default="whisper-base", max_length=100),
                ),
                (
                    "processing_time",
                    models.FloatField(help_text="Processing time in seconds"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
