from django.db import models


class TTSConfig(models.Model):
    """Singleton (pk=1) holding the user's preferred default voice.

    The manager is the producer of speech and may pass any voice it likes; when
    it omits one, speak() falls back to this preferred voice. Stored backend-side
    (not in the Electron store) precisely so the manager can honor it.
    """

    preferred_voice = models.CharField(max_length=64, default="af_heart")
    updated_at = models.DateTimeField(auto_now=True)

    @classmethod
    def get_solo(cls):
        obj, _ = cls.objects.get_or_create(pk=1)
        return obj


class Notification(models.Model):
    """A spoken notification generated by the manager (or system).

    Holds the text the manager wrote, the voice it chose, and a pointer to the
    synthesized WAV on disk (under MEDIA_ROOT). Integer pk keeps `?after=<id>`
    polling and ordering simple.
    """

    terminal_id = models.CharField(max_length=32, null=True, blank=True)
    terminal_name = models.CharField(max_length=200, null=True, blank=True)
    text = models.TextField()
    voice = models.CharField(max_length=64)
    speed = models.FloatField(default=1.0)
    source = models.CharField(max_length=32, default="manager")
    # Path relative to MEDIA_ROOT, e.g. "tts/42.wav".
    audio_path = models.CharField(max_length=300, blank=True, default="")
    duration_ms = models.IntegerField(default=0)
    played = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-created_at"]

    def __str__(self):
        return f"[{self.terminal_id}] {self.text[:60]}"
