# Generated by Django 4.2.7 on 2025-07-06 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todoitem",
            name="terminal_id",
            field=models.IntegerField(default=1),
        ),
    ]
