# Generated by Django 4.2.7 on 2025-08-06 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0002_add_terminal_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todogeneration",
            name="terminal_session",
        ),
        migrations.RemoveField(
            model_name="todoitem",
            name="terminal_session",
        ),
        migrations.AddField(
            model_name="todogeneration",
            name="terminal_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="todoitem",
            name="terminal_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
