# Generated by Django 4.2.7 on 2025-07-27 19:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PricingCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cache_key",
                    models.CharField(
                        help_text="Cache key for pricing data",
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("data", models.JSONField(help_text="Cached pricing data")),
                ("expires_at", models.DateTimeField(help_text="Cache expiration time")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "pricing_cache",
            },
        ),
        migrations.CreateModel(
            name="PricingData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(help_text="Session identifier", max_length=255),
                ),
                (
                    "execution_timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the ccusage command was executed",
                    ),
                ),
                (
                    "raw_output",
                    models.TextField(help_text="Raw output from ccusage command"),
                ),
                (
                    "parsed_data",
                    models.JSONField(default=dict, help_text="Parsed pricing data"),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total cost in USD",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "pricing_data",
                "ordering": ["-execution_timestamp"],
            },
        ),
    ]
