# Generated by Django 4.2.7
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_queue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagehistory',
            name='terminal_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='messagehistory',
            name='counter',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]