"""
Django settings for terminal_backend project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to FALSE (locked down). Opt into debug explicitly for local dev with
# DEBUG=true; the Docker backend sets DEBUG=false via .env / docker-compose.
DEBUG = os.environ.get('DEBUG', 'false').lower() == 'true'

# SECURITY WARNING: keep the secret key secret. A real key MUST be supplied via
# the environment when DEBUG is off; we only fall back to an insecure literal
# for local dev (DEBUG=true) so the venv flow keeps working without setup.
SECRET_KEY = os.environ.get('SECRET_KEY') or ''
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'django-insecure-local-dev-only'
    else:
        raise ImproperlyConfigured(
            'SECRET_KEY environment variable is required when DEBUG is false. '
            'Set it in .env (see .env.example).'
        )

# Host header allowlist. Env-driven (DJANGO_ALLOWED_HOSTS, comma-separated) so
# deployments can extend it; defaults cover the localhost-only access pattern
# used by the Electron app, the manager, and the container healthcheck.
ALLOWED_HOSTS = [
    h.strip()
    for h in os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
    if h.strip()
]


# Application definition

INSTALLED_APPS = [
    # Essential Django apps  
    "django.contrib.auth",        # Required by rest_framework
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third party apps
    "rest_framework",
    "corsheaders",
    # CORE FUNCTIONALITY ONLY - 4 essential apps:
    "pricing",              # ccusage pricing model (no live endpoint in Docker)
    "message_queue",        # health check pass-through
    "voice_transcription",  # audio transcribing
    "text_to_speech",       # Kokoro TTS + spoken notifications
    "frontend_control",     # frontend log shipping API

    # REMOVED: admin, channels, terminal, settings, todos, user_settings
    # No WebSocket consumers remain, so channels/CHANNEL_LAYERS are gone.
    # daphne (Dockerfile CMD) serves the HTTP-only ASGI app directly.
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",  # Add CORS middleware
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",  # Required by rest_framework
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "terminal_backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "terminal_backend.wsgi.application"
ASGI_APPLICATION = "terminal_backend.asgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
#
# Defaults to the bundled sqlite file so the non-docker venv flow keeps working
# unchanged. When DATABASE_URL or the discrete POSTGRES_* env vars are present
# (as set by docker-compose), Postgres is used instead.

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

_DATABASE_URL = os.environ.get("DATABASE_URL")
if _DATABASE_URL:
    import dj_database_url

    DATABASES["default"] = dj_database_url.parse(
        _DATABASE_URL, conn_max_age=600
    )
elif os.environ.get("POSTGRES_DB"):
    DATABASES["default"] = {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ["POSTGRES_DB"],
        "USER": os.environ.get("POSTGRES_USER", "postgres"),
        "PASSWORD": os.environ.get("POSTGRES_PASSWORD", ""),
        "HOST": os.environ.get("POSTGRES_HOST", "db"),
        "PORT": os.environ.get("POSTGRES_PORT", "5432"),
        "CONN_MAX_AGE": 600,
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# CORS settings
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "file://",  # Allow Auto-Injector app
]

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

# REST Framework settings
REST_FRAMEWORK = {
    # Defense-in-depth on top of the loopback bind. Defaults to open (AllowAny
    # behavior) when CCBOT_API_TOKEN is unset; requires the X-CCBOT-API-Token
    # header once that env var is set. See terminal_backend/api_security.py.
    'DEFAULT_PERMISSION_CLASSES': [
        'terminal_backend.api_security.TokenOrOpen',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.MultiPartParser',
        'rest_framework.parsers.FileUploadParser',
    ],
    # Cap the CPU/GPU-bound endpoints so a runaway/abusive caller can't exhaust
    # the single inference worker. Applied per-view (see TTSSpeakThrottle /
    # VoiceTranscribeThrottle); rates are generous — well above normal
    # manager/frontend bursts. GET polling endpoints are NOT throttled.
    'DEFAULT_THROTTLE_RATES': {
        'tts_speak': os.environ.get('THROTTLE_TTS_SPEAK', '120/min'),
        'voice_transcribe': os.environ.get('THROTTLE_VOICE_TRANSCRIBE', '60/min'),
    },
}

# Force synchronous execution for compatibility
import os
os.environ.setdefault('DJANGO_ALLOW_ASYNC_UNSAFE', 'true')

# Media files configuration for voice recordings
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
