# Generated by Django 5.0.1 on 2026-06-23 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminal_id', models.CharField(blank=True, max_length=32, null=True)),
                ('terminal_name', models.CharField(blank=True, max_length=200, null=True)),
                ('text', models.TextField()),
                ('voice', models.CharField(max_length=64)),
                ('speed', models.FloatField(default=1.0)),
                ('source', models.CharField(default='manager', max_length=32)),
                ('audio_path', models.CharField(blank=True, default='', max_length=300)),
                ('duration_ms', models.IntegerField(default=0)),
                ('played', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
