# Generated by Django 5.0.1 on 2026-06-23 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_to_speech', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TTSConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_voice', models.CharField(default='af_heart', max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
