# Generated by Django 4.2.7 on 2025-08-06 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0003_remove_todogeneration_terminal_session_and_more"),
        ("message_queue", "0004_remove_messagehistory_terminal_session_and_more"),
        ("terminal", "0002_applicationstatistics_terminalsession_color_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ApplicationStatistics",
        ),
        migrations.DeleteModel(
            name="TerminalCommand",
        ),
        migrations.DeleteModel(
            name="TerminalSession",
        ),
    ]
